#!/usr/bin/python
import re
import commands


def get_keychain_pass(account=None, server=None):
    params = {
        'security': '/usr/bin/security',
        'command':  'find-internet-password',
        'account':  account,
        'server':   server,
        'keychain': '/Users/denis/Library/Keychains/login.keychain',
    }

    command = (
        "sudo -u denis %(security)s -v %(command)s -g -a %(account)s "
        "-s %(server)s %(keychain)s | grep 'password:'"
    ) % params
    outtext = commands.getoutput(command)

    if 'The specified item could not be found' in outtext:
        print
        print "%s -> %s must first be added to the keychain." % (
            account, server
        )
        print "Use 'internet password' by adding a https:// in front of"
        print "%s in the first field or it won't work" % server
        print

        raise KeyError('Not found in keychain')

    pw = re.compile(r'password: "(.*)"')

    matches = (pw.match(line) for line in outtext.split('\n'))
    match = (m for m in matches if m is not None).next()

    return match.group(1) if match else None
