#!/bin/sh
#
# Set-up Sublime settings + packages sync over Dropbox
#
# Will sync settings + Installed plug-ins
#
# Tested on OSX - should support Linux too as long as
# you set-up correct SOURCE folder
#
# Copyright 2012 Mikko Ohtamaa http://opensourcehacker.com
# Licensed under WTFPL
#

# Note: If there is an existing installation in Dropbox,
# it will replace settings on a local computer

# No Warranty! Use on your own risk. Take backup of Library/Application Support/Sublime Text 3 folder first.

DROPBOX="$HOME/Dropbox"

# Where do we put Sublime settings in our Dropbox
SYNC_FOLDER="$DROPBOX/Sublime 3"

# Where Sublime settings have been installed
if [ `uname` = "Darwin" ];then
        SOURCE="$HOME/Library/Application Support/Sublime Text 3"
elif [ `uname` = "Linux" ];then
        SOURCE="$HOME/.config/sublime-text"
else
        echo "Unknown operating system"
        exit 0
fi

# Check that settings really exist on this computer
if [ ! -e "$SOURCE/Packages/User" ]; then
        echo "Could not find $SOURCE/User"
        exit 0
fi

# Detect that we don't try to install twice and screw up
if [ -L "$SOURCE/Packages/User" ] ; then
        echo "Dropbox settings already symlinked"
        exit 0
fi

# XXX: Disabled Settings/ folder syncing as looks like
# Sublime keeps only license and .sublime_session files -
# the latter
# which are autosaved and would cause unnecessary conflicts
# and traffic

# Dropbox has not been set-up on any computer before?
if [ ! -e "$SYNC_FOLDER" ] ; then
        echo "Setting up Dropbox sync folder"
        
        mkdir -p "$SYNC_FOLDER/Packages/"
        mv "$SOURCE/Packages/User" "$SYNC_FOLDER/Packages/"
fi

# Symlink settings folders from Drobox
# The "Installed Packages" and "Packages" was never
# created inside of Dropbox folder. These lines are not working.
# Fixed to the correct folder.

ln -s "$SYNC_FOLDER/Packages/User" "$SOURCE/Packages/"
